In [1]:
import pandas as pd
pd.options.display.max_columns = None
import re
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
from sklearn.impute import KNNImputer

In [2]:
df = pd.read_csv("../Archivos/no_profesionales.csv", index_col= 0)

In [3]:
df.head(2)

,edad,genero,pais,estudios,puesto_trabajo,experiencia,lenguaje_recomendado,experiencia_ML,industria,tamaño_empresa,salario,herramienta_DA,lenguaje_utilizado,IDE,herramientas_visualizacion,Q16_frame_ml,Q17_alg_ml,Q32_prod_bigdata,Q34_herramientas_bi,Q28,q10_notebooks,q39_plat_compartir_trabajo,q40_plat_cursos,q27_plat_familiar_cloud_computing,q29b_productos_familiar_cloud_computing,q31b_productos_familiar_ml,q32b_productos_familiar_bd,q34b_herramientas_familiar_bi,q36b_cat_herramientas_familiar_ml,q37b_cat_herramientas_familiar_ml_aut,q38b_herramientas_familiar_gest_exp_ml
5,25-29,Woman,India,I prefer not to answer,Currently not employed,< 1 years,Python,< 1 year,NaN,NaN,NaN,"Local development environments (RStudio, Jupyt...",Python,"Jupyter (JupyterLab, Jupyter Notebooks, etc) ,...","Matplotlib ,Seaborn ,Ggplot / ggplot2","Scikit-learn , TensorFlow ,Keras ,PyTorch ,Fas...","Linear or Logistic Regression, Decision Trees ...",NaN,NaN,NaN,Colab Notebooks,NaN,"Cloud-certification programs (direct from AWS,...","Amazon Web Services (AWS) , Microsoft Azure ,...","Amazon Elastic Compute Cloud (EC2) , Microsof...","Amazon SageMaker , Azure Machine Learning Stu...",Microsoft Azure SQL Database,Tableau,Automation of full ML pipelines (e.g. Google C...,"Google Cloud AutoML , Azure Automated Machin...","Guild.ai , MLflow"
6,18-21,Woman,India,Some college/university study without earning ...,Student,1-3 years,Python,< 1 year,NaN,NaN,NaN,NaN,"C++, Java, Javascript","Visual Studio ,Visual Studio Code (VSCode) ,Ju...",Geoplotlib,Fast.ai,NaN,NaN,NaN,NaN,"Kaggle Notebooks,Google Cloud Notebooks (AI P...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df.salario.isnull().sum()*100/df.shape[0]

100.0